### ISSUE TITLE
Can't Load Any Page That Requires Maps As the First Page

### ISSUE THREAD

**Issue by akaplo** [umts/pvta-multiplatform#371]
Navigating to any page **from MyBuses* (or any other page that doesn't immediately require google maps), works.  Loading it as the first page via its URL, however, doesn't:

To reproduce: 
1a. go to https://m.pvta.com/#/route/20030/map (or any RouteId will do)
1b. go to https://m.pvta.com/#/plan-trip
1c. go to https://m.pvta.com/#/stop/56/map (or any StopId will do)

2. Observe the white screen and stack trace in developer console.

I assume this is somehow caused by #351.

EXCEPTION: Uncaught (in promise): ReferenceError: google is not defined
ReferenceError: google is not defined
    at new t (https://m.pvta.com/build/main.js:18:18089)
    at new t (https://m.pvta.com/build/main.js:53:23741)
    at e.createInternal (https://m.pvta.com/build/main.js:53:24482)
    at e.t.createHostView (https://m.pvta.com/build/main.js:2:12917)
    at t.create (https://m.pvta.com/build/main.js:2:10789)
    at e._viewInit (https://m.pvta.com/build/main.js:21:8190)
    at e._nextTrns (https://m.pvta.com/build/main.js:21:5900)
    at e._queueTrns (https://m.pvta.com/build/main.js:21:5384)
    at e._setPages (https://m.pvta.com/build/main.js:21:4480)
    at e.setPages (https://m.pvta.com/build/main.js:21:4361)
    at e.ngAfterViewInit (https://m.pvta.com/build/main.js:13:21540)
    at e.detectChangesInternal (https://m.pvta.com/build/main.js:44:29444)
    at e.t.detectChanges (https://m.pvta.com/build/main.js:2:17378)
    at e.t.internalDetectChanges (https://m.pvta.com/build/main.js:2:17171)
    at e.detectChangesInternal (https://m.pvta.com/build/main.js:44:13691)

**Comment by akaplo** [comment]
Not a problem with 1.x because the `<script>` tag that loads the Maps API is a blocking call inside of `<head>`, before any JS is ever run.  

#351, while clean and efficient in most regards, adds the same tag to the HTML during JS's runtime. @werebus and I are both independently researching solutions.

**Comment by akaplo** [comment]
Closed by #375.
